//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_USER_GROUP_DET
    {
        public int id { get; set; }
        public int group_id { get; set; }
        public int user_id { get; set; }
        public string user_type { get; set; }
        public System.DateTime date_created { get; set; }
    
        public virtual SYS_USER SYS_USER { get; set; }
        public virtual SYS_USER_GROUP SYS_USER_GROUP { get; set; }
    }
}
