//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class accessEntities : DbContext
    {
        public accessEntities()
            : base("name=accessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SYS_Module> SYS_Module { get; set; }
        public virtual DbSet<sys_module_type> sys_module_type { get; set; }
    
        public virtual int SP_FUNCTION_ACCESS(string mODULENAME, string fUNCTION, string aPP_MODULE, Nullable<int> uSERID, ObjectParameter aCCESS)
        {
            var mODULENAMEParameter = mODULENAME != null ?
                new ObjectParameter("MODULENAME", mODULENAME) :
                new ObjectParameter("MODULENAME", typeof(string));
    
            var fUNCTIONParameter = fUNCTION != null ?
                new ObjectParameter("FUNCTION", fUNCTION) :
                new ObjectParameter("FUNCTION", typeof(string));
    
            var aPP_MODULEParameter = aPP_MODULE != null ?
                new ObjectParameter("APP_MODULE", aPP_MODULE) :
                new ObjectParameter("APP_MODULE", typeof(string));
    
            var uSERIDParameter = uSERID.HasValue ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_FUNCTION_ACCESS", mODULENAMEParameter, fUNCTIONParameter, aPP_MODULEParameter, uSERIDParameter, aCCESS);
        }
    
        public virtual int SP_MODULE_ACCESS(string mODULENAME, Nullable<int> mODULETYPE, Nullable<int> uSERID, Nullable<int> mODULE_APP, ObjectParameter aCCESS, ObjectParameter aCTIVE)
        {
            var mODULENAMEParameter = mODULENAME != null ?
                new ObjectParameter("MODULENAME", mODULENAME) :
                new ObjectParameter("MODULENAME", typeof(string));
    
            var mODULETYPEParameter = mODULETYPE.HasValue ?
                new ObjectParameter("MODULETYPE", mODULETYPE) :
                new ObjectParameter("MODULETYPE", typeof(int));
    
            var uSERIDParameter = uSERID.HasValue ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(int));
    
            var mODULE_APPParameter = mODULE_APP.HasValue ?
                new ObjectParameter("MODULE_APP", mODULE_APP) :
                new ObjectParameter("MODULE_APP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODULE_ACCESS", mODULENAMEParameter, mODULETYPEParameter, uSERIDParameter, mODULE_APPParameter, aCCESS, aCTIVE);
        }
    }
}
