//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjustmentFile
    {
        public int AdjusmentFile_ID { get; set; }
        public Nullable<int> Emp_ID { get; set; }
        public Nullable<int> Adjustment_ID { get; set; }
        public Nullable<System.DateTime> Trandate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Taxable { get; set; }
        public bool Status { get; set; }
        public int UserID { get; set; }
        public bool billable { get; set; }
        public int adjustment_classification_id { get; set; }
    
        public virtual Adjustment Adjustment { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual SYS_USER SYS_USER { get; set; }
    }
}
