//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adjustment
    {
        public int Adjustment_ID { get; set; }
        public string Adjustment_Desc { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int client_id { get; set; }
        public bool status { get; set; }
        public bool billable { get; set; }
        public int adjustment_classification_id { get; set; }
    
        public virtual REC_CLIENT REC_CLIENT { get; set; }
        public virtual SYS_USER SYS_USER { get; set; }
        public virtual ADJUSTMENT_CLASSIFICATION ADJUSTMENT_CLASSIFICATION { get; set; }
    }
}
