//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branch()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int Branch_ID { get; set; }
        public string Branch_Desc { get; set; }
        public int UserID { get; set; }
        public int client_id { get; set; }
        public bool status { get; set; }
        public decimal no_of_days { get; set; }
        public System.DateTime date_created { get; set; }
        public string region_name { get; set; }
        public Nullable<decimal> region_longitude { get; set; }
        public Nullable<decimal> region_latitude { get; set; }
        public Nullable<int> allowed_radius_meter { get; set; }
    
        public virtual REC_CLIENT REC_CLIENT { get; set; }
        public virtual SYS_USER SYS_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
