//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deduction
    {
        public int Ded_id { get; set; }
        public string Ded_Desc { get; set; }
        public int UserID { get; set; }
        public int client_id { get; set; }
        public bool status { get; set; }
        public System.DateTime date_Created { get; set; }
    
        public virtual REC_CLIENT REC_CLIENT { get; set; }
        public virtual SYS_USER SYS_USER { get; set; }
    }
}
