//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Degree
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Degree()
        {
            this.REC_CANDIDATE_EDUCATION = new HashSet<REC_CANDIDATE_EDUCATION>();
        }
    
        public int DegreeID { get; set; }
        public string DegreeName { get; set; }
        public bool status { get; set; }
        public int UserCreated { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> UserUpdated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public int country_id { get; set; }
    
        public virtual SYS_USER SYS_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REC_CANDIDATE_EDUCATION> REC_CANDIDATE_EDUCATION { get; set; }
    }
}
