//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Benefits_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee_Benefits_Type()
        {
            this.Employee_Benefits = new HashSet<Employee_Benefits>();
        }
    
        public int id { get; set; }
        public string benefits_type { get; set; }
        public bool status { get; set; }
        public Nullable<int> user_created { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<int> user_modified { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Benefits> Employee_Benefits { get; set; }
    }
}
