//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.REC_CANDIDATE_EMPLOYEE_LINK = new HashSet<REC_CANDIDATE_EMPLOYEE_LINK>();
            this.EmployeeLeaveMonitorings = new HashSet<EmployeeLeaveMonitoring>();
            this.P_Leave = new HashSet<P_Leave>();
            this.EmployeeLoanMasters = new HashSet<EmployeeLoanMaster>();
            this.Employee_Replacement_HD = new HashSet<Employee_Replacement_HD>();
            this.Employee_Separation = new HashSet<Employee_Separation>();
            this.Employee_Separation1 = new HashSet<Employee_Separation>();
            this.REC_NEW_HIRED_EMPLOYEE = new HashSet<REC_NEW_HIRED_EMPLOYEE>();
            this.HELPDESK_CONCERN = new HashSet<HELPDESK_CONCERN>();
        }
    
        public int Emp_ID { get; set; }
        public int EmpType_ID { get; set; }
        public int EmpRank_ID { get; set; }
        public int Branch_ID { get; set; }
        public int Department_ID { get; set; }
        public string Position { get; set; }
        public int Shift_ID { get; set; }
        public Nullable<int> PayrollGroup_ID { get; set; }
        public Nullable<int> SalaryType_ID { get; set; }
        public string Emp_No { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Middlename { get; set; }
        public string Address { get; set; }
        public string Prov_Address { get; set; }
        public string Contact_No { get; set; }
        public string Gender { get; set; }
        public string CivilStatus { get; set; }
        public string Companycode { get; set; }
        public string Citizenship { get; set; }
        public string Spouse { get; set; }
        public string Spouse_comp { get; set; }
        public string Spouse_address { get; set; }
        public string Religion { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> Datehired { get; set; }
        public Nullable<System.DateTime> Dateregular { get; set; }
        public Nullable<System.DateTime> Dateresigned { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Birthplace { get; set; }
        public string TaxExemption { get; set; }
        public string Account_no { get; set; }
        public string Tax_no { get; set; }
        public string SSS_no { get; set; }
        public string Philhealth_no { get; set; }
        public string Pagibig_no { get; set; }
        public string Contact_person { get; set; }
        public string Contact_Address { get; set; }
        public string Contact_relation { get; set; }
        public string Contact_Telno { get; set; }
        public bool IsOtRegular { get; set; }
        public Nullable<short> ActiveInactive { get; set; }
        public int UserID { get; set; }
        public Nullable<decimal> MonthlySalary { get; set; }
        public Nullable<decimal> RiceAllowance { get; set; }
        public Nullable<decimal> MealAllowance { get; set; }
        public Nullable<decimal> AnnualTaxExcemp { get; set; }
        public Nullable<decimal> Allowance { get; set; }
        public decimal PagIbigCont { get; set; }
        public Nullable<decimal> Cola { get; set; }
        public Nullable<bool> IsIncludePayroll { get; set; }
        public decimal ManualTaxDed { get; set; }
        public Nullable<int> CompID { get; set; }
        public byte[] ImageFile { get; set; }
        public string ResignedRemarks { get; set; }
        public string Hobbies { get; set; }
        public Nullable<System.DateTime> ContractStart { get; set; }
        public Nullable<System.DateTime> ContractEnd { get; set; }
        public int CityID { get; set; }
        public int ProvinceID { get; set; }
        public int client_id { get; set; }
        public string pay_type { get; set; }
        public Nullable<int> bank_id { get; set; }
        public int contracttype_id { get; set; }
        public int employee_processingtype { get; set; }
        public Nullable<decimal> car_allowance { get; set; }
        public Nullable<decimal> commission { get; set; }
        public bool is_minimum { get; set; }
        public int employer_id { get; set; }
        public decimal CTPA { get; set; }
        public decimal SEA { get; set; }
        public string remarks { get; set; }
        public bool ismanual_tax { get; set; }
        public bool ismanual_pagibigcont { get; set; }
        public bool ismanual_ssscont { get; set; }
        public bool ismanual_philhealthcont { get; set; }
        public decimal sss_manualcont { get; set; }
        public decimal philhealth_manualcont { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<int> user_modified { get; set; }
        public System.DateTime date_encoded { get; set; }
        public bool is_confidential { get; set; }
        public int restday_id { get; set; }
        public string card_number { get; set; }
        public bool with_VAT { get; set; }
        public Nullable<decimal> tax_percentage { get; set; }
        public int func_id { get; set; }
        public Nullable<System.DateTime> card_no_validity { get; set; }
    
        public virtual SYS_USER SYS_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REC_CANDIDATE_EMPLOYEE_LINK> REC_CANDIDATE_EMPLOYEE_LINK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLeaveMonitoring> EmployeeLeaveMonitorings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_Leave> P_Leave { get; set; }
        public virtual REC_CLIENT REC_CLIENT { get; set; }
        public virtual REC_CLIENT REC_CLIENT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLoanMaster> EmployeeLoanMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Replacement_HD> Employee_Replacement_HD { get; set; }
        public virtual Department Department { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual REC_CONTRACT_TYPE REC_CONTRACT_TYPE { get; set; }
        public virtual REC_SOURCE_TYPE REC_SOURCE_TYPE { get; set; }
        public virtual EmployeeType EmployeeType { get; set; }
        public virtual EmployeeRank EmployeeRank { get; set; }
        public virtual Shift Shift { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Separation> Employee_Separation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Separation> Employee_Separation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REC_NEW_HIRED_EMPLOYEE> REC_NEW_HIRED_EMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HELPDESK_CONCERN> HELPDESK_CONCERN { get; set; }
        public virtual AreaLibrary AreaLibrary { get; set; }
        public virtual AreaLibrary AreaLibrary1 { get; set; }
    }
}
