//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Benefits_Adjustment_File_Link
    {
        public int id { get; set; }
        public int benefit_id { get; set; }
        public int adjfile_id { get; set; }
        public System.DateTime date_created { get; set; }
        public int user_created { get; set; }
    }
}
