//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Floating_Status
    {
        public int id { get; set; }
        public int emp_id { get; set; }
        public bool isfloating { get; set; }
        public int floating_reasonid { get; set; }
        public System.DateTime floating_date { get; set; }
        public string remarks { get; set; }
        public int user_id { get; set; }
        public System.DateTime date_updated { get; set; }
        public bool with_separation_pay { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<System.DateTime> date_unfloat { get; set; }
        public int client_id { get; set; }
    
        public virtual FloatingReason FloatingReason { get; set; }
    }
}
