//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Benefits
    {
        public int id { get; set; }
        public int emp_id { get; set; }
        public int benefit_type_id { get; set; }
        public int benefit_class_id { get; set; }
        public int benefit_cat_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public System.DateTime effective_date { get; set; }
        public System.DateTime benefits_start_date { get; set; }
        public Nullable<int> adj_id { get; set; }
        public Nullable<bool> is_taxable { get; set; }
        public Nullable<bool> is_billable { get; set; }
        public Nullable<bool> benefit_status { get; set; }
        public string remarks { get; set; }
        public Nullable<int> user_created { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<int> user_modified { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public int client_id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee_Benefits_Type Employee_Benefits_Type { get; set; }
        public virtual REC_CLIENT REC_CLIENT { get; set; }
    }
}
