//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeaveMonitoring
    {
        public int ID { get; set; }
        public int EmpID { get; set; }
        public int LeaveTypeID { get; set; }
        public decimal EntitleLeave { get; set; }
        public decimal RemainingLeave { get; set; }
        public decimal UsedLeave { get; set; }
        public decimal BalanceLeave { get; set; }
        public int MonthEntitled { get; set; }
        public int YearEntitled { get; set; }
        public System.DateTime ValidDateFrom { get; set; }
        public Nullable<System.DateTime> ValidDateTo { get; set; }
        public int UserId { get; set; }
        public int client_id { get; set; }
        public bool status { get; set; }
        public System.DateTime date_added { get; set; }
        public decimal credit_earned_per_month { get; set; }
        public bool is_convertable { get; set; }
        public bool auto_reset_per_year { get; set; }
        public string when_credit_is_earned { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual SYS_USER SYS_USER { get; set; }
        public virtual REC_CLIENT REC_CLIENT { get; set; }
    }
}
