//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Replacement_HD
    {
        public int id { get; set; }
        public int emp_id { get; set; }
        public System.DateTime replacement_date { get; set; }
        public int status { get; set; }
        public string remarks { get; set; }
        public int user_id { get; set; }
        public System.DateTime date_created { get; set; }
        public int floating_id { get; set; }
        public int separation_id { get; set; }
        public int jo_id { get; set; }
        public bool is_retracted { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual SYS_USER SYS_USER { get; set; }
        public virtual SYS_USER SYS_USER1 { get; set; }
    }
}
