//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLoanMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeLoanMaster()
        {
            this.LoanTransactions = new HashSet<LoanTransaction>();
        }
    
        public int LoanID { get; set; }
        public int EmpID { get; set; }
        public int LoanTypeID { get; set; }
        public System.DateTime DateLoan { get; set; }
        public decimal LoanAmount { get; set; }
        public decimal Balance { get; set; }
        public decimal Amortization { get; set; }
        public bool LoanStat { get; set; }
        public bool DeductStatus { get; set; }
        public decimal DeductAmnt { get; set; }
        public int UserID { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> loan_start { get; set; }
        public System.DateTime date_added { get; set; }
        public Nullable<int> user_modified { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public string guid { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual SYS_USER SYS_USER { get; set; }
        public virtual LoanType LoanType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanTransaction> LoanTransactions { get; set; }
    }
}
