//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Separation
    {
        public int ID { get; set; }
        public int EmpID { get; set; }
        public int Reason_ID { get; set; }
        public string Remarks { get; set; }
        public System.DateTime Separation_Date { get; set; }
        public Nullable<System.DateTime> Clearance_Date { get; set; }
        public Nullable<bool> With_Clearance { get; set; }
        public Nullable<System.DateTime> Quitclaim_Date { get; set; }
        public Nullable<bool> With_Quitclaim { get; set; }
        public Nullable<System.DateTime> COE_Date { get; set; }
        public Nullable<bool> With_COE { get; set; }
        public Nullable<System.DateTime> Termination_Date { get; set; }
        public Nullable<bool> With_Termination { get; set; }
        public Nullable<bool> Is_History { get; set; }
        public Nullable<bool> Overall_Status { get; set; }
        public Nullable<System.DateTime> Overall_Status_Date { get; set; }
        public int user_id { get; set; }
        public System.DateTime date_modified { get; set; }
        public int client_id { get; set; }
        public Nullable<System.DateTime> date_is_history_updated { get; set; }
        public int user_id_is_history_updated { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Separation_Reason Separation_Reason { get; set; }
    }
}
