//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HELPDESK_CONCERN_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HELPDESK_CONCERN_TYPE()
        {
            this.HELPDESK_CONCERN = new HashSet<HELPDESK_CONCERN>();
        }
    
        public int id { get; set; }
        public decimal sort_no { get; set; }
        public string concern_description { get; set; }
        public string department { get; set; }
        public bool status { get; set; }
        public int user_id { get; set; }
        public System.DateTime date_created { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HELPDESK_CONCERN> HELPDESK_CONCERN { get; set; }
        public virtual SYS_USER SYS_USER { get; set; }
    }
}
