//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HELPDESK_CONCERN_THREAD
    {
        public int id { get; set; }
        public int concern_id { get; set; }
        public string user_type { get; set; }
        public int user_Id { get; set; }
        public bool status { get; set; }
        public System.DateTime date_created { get; set; }
        public string remarks { get; set; }
        public string file_location { get; set; }
        public string file_name { get; set; }
        public string content_type { get; set; }
        public Nullable<System.DateTime> date_uploaded { get; set; }
    
        public virtual HELPDESK_CONCERN HELPDESK_CONCERN { get; set; }
    }
}
