//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HELPDESK_CONCERN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HELPDESK_CONCERN()
        {
            this.HELPDESK_CONCERN_THREAD = new HashSet<HELPDESK_CONCERN_THREAD>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public string user_type { get; set; }
        public int concern_type_id { get; set; }
        public string concern_description { get; set; }
        public bool post_status { get; set; }
        public bool file_status { get; set; }
        public bool concern_status { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> date_completed { get; set; }
        public Nullable<System.DateTime> date_posted { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual HELPDESK_CONCERN_TYPE HELPDESK_CONCERN_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HELPDESK_CONCERN_THREAD> HELPDESK_CONCERN_THREAD { get; set; }
    }
}
