//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class apwdbEntities : DbContext
    {
        public apwdbEntities()
            : base("name=apwdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<REC_USER_LOG> REC_USER_LOG { get; set; }
        public virtual DbSet<sys_company> sys_company { get; set; }
        public virtual DbSet<SYS_USER> SYS_USER { get; set; }
        public virtual DbSet<SYS_USER_GROUP> SYS_USER_GROUP { get; set; }
        public virtual DbSet<SYS_USER_GROUP_DET> SYS_USER_GROUP_DET { get; set; }
        public virtual DbSet<REC_CANDIDATE> REC_CANDIDATE { get; set; }
        public virtual DbSet<REC_CANDIDATE_EMPLOYEE_LINK> REC_CANDIDATE_EMPLOYEE_LINK { get; set; }
        public virtual DbSet<AreaLibrary> AreaLibraries { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<EmployeeType> EmployeeTypes { get; set; }
        public virtual DbSet<EMPLOYER> EMPLOYERs { get; set; }
        public virtual DbSet<REC_CLIENT> REC_CLIENT { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<REC_CANDIDATE_DOCUMENT> REC_CANDIDATE_DOCUMENT { get; set; }
        public virtual DbSet<REC_CANDIDATE_EDUCATION> REC_CANDIDATE_EDUCATION { get; set; }
        public virtual DbSet<REC_CANDIDATE_EMPLOYMENT> REC_CANDIDATE_EMPLOYMENT { get; set; }
        public virtual DbSet<REC_CANDIDATE_SKILL> REC_CANDIDATE_SKILL { get; set; }
        public virtual DbSet<REC_CANDIDATE_TRAINING> REC_CANDIDATE_TRAINING { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<SchoolLevel> SchoolLevels { get; set; }
        public virtual DbSet<Degree> Degrees { get; set; }
        public virtual DbSet<REC_Skill> REC_Skill { get; set; }
    
        public virtual ObjectResult<USP_H_GET_EMPLOYEE_MONITORING_Result1> USP_H_GET_EMPLOYEE_MONITORING(string kEYWORD, Nullable<bool> bY_CLIENT, Nullable<int> cLIENT_ID, Nullable<int> pageNumber, Nullable<int> pageSize, Nullable<int> cOMPANY_ID)
        {
            var kEYWORDParameter = kEYWORD != null ?
                new ObjectParameter("KEYWORD", kEYWORD) :
                new ObjectParameter("KEYWORD", typeof(string));
    
            var bY_CLIENTParameter = bY_CLIENT.HasValue ?
                new ObjectParameter("BY_CLIENT", bY_CLIENT) :
                new ObjectParameter("BY_CLIENT", typeof(bool));
    
            var cLIENT_IDParameter = cLIENT_ID.HasValue ?
                new ObjectParameter("CLIENT_ID", cLIENT_ID) :
                new ObjectParameter("CLIENT_ID", typeof(int));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var cOMPANY_IDParameter = cOMPANY_ID.HasValue ?
                new ObjectParameter("COMPANY_ID", cOMPANY_ID) :
                new ObjectParameter("COMPANY_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_H_GET_EMPLOYEE_MONITORING_Result1>("USP_H_GET_EMPLOYEE_MONITORING", kEYWORDParameter, bY_CLIENTParameter, cLIENT_IDParameter, pageNumberParameter, pageSizeParameter, cOMPANY_IDParameter);
        }
    }
}
