//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class INDUSTRY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INDUSTRY()
        {
            this.REC_CLIENT = new HashSet<REC_CLIENT>();
            this.REC_CANDIDATE_EMPLOYMENT = new HashSet<REC_CANDIDATE_EMPLOYMENT>();
            this.REC_JOB_ORDER = new HashSet<REC_JOB_ORDER>();
        }
    
        public int id { get; set; }
        public string industry_name { get; set; }
        public bool status { get; set; }
        public int user_id { get; set; }
        public System.DateTime date_created { get; set; }
        public string psic_code { get; set; }
        public int country_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REC_CLIENT> REC_CLIENT { get; set; }
        public virtual SYS_USER SYS_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REC_CANDIDATE_EMPLOYMENT> REC_CANDIDATE_EMPLOYMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REC_JOB_ORDER> REC_JOB_ORDER { get; set; }
    }
}
