//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanTransaction
    {
        public int ID { get; set; }
        public Nullable<int> LoanID { get; set; }
        public Nullable<int> PayrollID { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual EmployeeLoanMaster EmployeeLoanMaster { get; set; }
    }
}
