//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanType()
        {
            this.EmployeeLoanMasters = new HashSet<EmployeeLoanMaster>();
        }
    
        public int LoanType_ID { get; set; }
        public string LoanType_Desc { get; set; }
        public int UserID { get; set; }
        public System.DateTime date_created { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLoanMaster> EmployeeLoanMasters { get; set; }
        public virtual SYS_USER SYS_USER { get; set; }
    }
}
