//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OvertimeBasi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OvertimeBasi()
        {
            this.REC_CLIENT_SETUP = new HashSet<REC_CLIENT_SETUP>();
        }
    
        public int Id { get; set; }
        public string OvertimeBasis_Desc { get; set; }
        public Nullable<decimal> Min_Time { get; set; }
        public Nullable<decimal> Succeeding_Time { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REC_CLIENT_SETUP> REC_CLIENT_SETUP { get; set; }
    }
}
