//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Leave
    {
        public int P_LeaveID { get; set; }
        public int EmpID { get; set; }
        public int LeaveTypeId { get; set; }
        public bool is_EmergencyLeave { get; set; }
        public System.DateTime DateFiled { get; set; }
        public System.DateTime LeaveFrom { get; set; }
        public System.DateTime LeaveTo { get; set; }
        public string FromAMPM { get; set; }
        public string ToAMPM { get; set; }
        public decimal LeaveDays { get; set; }
        public string Reason { get; set; }
        public string Remarks { get; set; }
        public bool IsHalfDay { get; set; }
        public Nullable<bool> Status { get; set; }
        public int FileStatus { get; set; }
        public bool IsRejected { get; set; }
        public bool HrReceive { get; set; }
        public Nullable<bool> WithAttachment { get; set; }
        public Nullable<bool> IsWithPay { get; set; }
        public Nullable<bool> IS_POST_TO_HRAD { get; set; }
        public string REMARKS_WHY_HRAD { get; set; }
        public int client_id { get; set; }
        public Nullable<int> user_modified { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<System.DateTime> date_posted { get; set; }
        public Nullable<System.DateTime> date_approved { get; set; }
        public Nullable<System.DateTime> date_rejected { get; set; }
        public bool first_half { get; set; }
        public bool second_half { get; set; }
        public bool firstday_secondhalf { get; set; }
        public bool lastday_firsthalf { get; set; }
        public bool is_cancel { get; set; }
        public int user_id { get; set; }
        public string filing_extension { get; set; }
        public string approval_extension { get; set; }
        public string guid { get; set; }
        public int dtr_id { get; set; }
        public int department_id { get; set; }
        public Nullable<bool> approved_by_payroll { get; set; }
        public Nullable<System.DateTime> date_approved_by_payroll { get; set; }
        public Nullable<bool> reject_by_payroll { get; set; }
        public Nullable<System.DateTime> date_rejected_by_payroll { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual SYS_USER SYS_USER { get; set; }
        public virtual REC_CLIENT REC_CLIENT { get; set; }
    }
}
