//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortalUser
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int EmpID { get; set; }
        public bool Status { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string EmailAddress { get; set; }
        public string UserType { get; set; }
        public Nullable<System.DateTime> DateReg { get; set; }
        public string ResetKey { get; set; }
        public Nullable<System.DateTime> date_reset_requested { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
