//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_JOB_ORDER
    {
        public int id { get; set; }
        public int client_id { get; set; }
        public System.DateTime jo_date { get; set; }
        public string position { get; set; }
        public int quantity { get; set; }
        public string eto { get; set; }
        public Nullable<decimal> estimated_salary { get; set; }
        public Nullable<decimal> fee_rate { get; set; }
        public Nullable<int> jo_status { get; set; }
        public string jq_location { get; set; }
        public string jd_location { get; set; }
        public int lost_id { get; set; }
        public string lost_remarks { get; set; }
        public int user_created { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public int user_modified { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<int> contracttype_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.DateTime> date_complete { get; set; }
        public string from_what { get; set; }
        public int industry_id { get; set; }
        public int function_id { get; set; }
        public int hold_qty { get; set; }
        public int lost_qty { get; set; }
        public int cancel_qty { get; set; }
        public string po_number { get; set; }
        public Nullable<System.DateTime> lost_date { get; set; }
        public int purpose_type_id { get; set; }
        public string guid { get; set; }
    
        public virtual INDUSTRY INDUSTRY { get; set; }
        public virtual REC_CLIENT REC_CLIENT { get; set; }
        public virtual REC_CONTRACT_TYPE REC_CONTRACT_TYPE { get; set; }
        public virtual SYS_USER SYS_USER { get; set; }
        public virtual SYS_USER SYS_USER1 { get; set; }
    }
}
