//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_Skill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REC_Skill()
        {
            this.REC_CANDIDATE_SKILL = new HashSet<REC_CANDIDATE_SKILL>();
        }
    
        public int id { get; set; }
        public int function_id { get; set; }
        public string skill_type { get; set; }
        public string Skill_description { get; set; }
        public string Skill_details { get; set; }
        public bool status { get; set; }
        public int user_id { get; set; }
        public System.DateTime date_created { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REC_CANDIDATE_SKILL> REC_CANDIDATE_SKILL { get; set; }
        public virtual SYS_USER SYS_USER { get; set; }
    }
}
