//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_CANDIDATE_SKILL
    {
        public int id { get; set; }
        public int candidate_id { get; set; }
        public int skill_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime date_created { get; set; }
    
        public virtual REC_CANDIDATE REC_CANDIDATE { get; set; }
        public virtual SYS_USER SYS_USER { get; set; }
        public virtual REC_Skill REC_Skill { get; set; }
    }
}
