//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_CANDIDATE_EDUCATION
    {
        public int candidate_id { get; set; }
        public string School_Level { get; set; }
        public string School_Name { get; set; }
        public string School_Remarks { get; set; }
        public string School_Grade { get; set; }
        public Nullable<System.DateTime> School_From { get; set; }
        public Nullable<System.DateTime> School_To { get; set; }
        public int School_Id { get; set; }
        public string Awards { get; set; }
        public int SchoolLibID { get; set; }
        public int SchoolLevelID { get; set; }
        public Nullable<int> DegreeID { get; set; }
        public Nullable<bool> Graduated { get; set; }
        public int user_id { get; set; }
        public System.DateTime date_created { get; set; }
    
        public virtual REC_CANDIDATE REC_CANDIDATE { get; set; }
        public virtual Degree Degree { get; set; }
        public virtual SchoolLevel SchoolLevel { get; set; }
        public virtual School School { get; set; }
    }
}
