//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_CANDIDATE_EMPLOYEE_LINK
    {
        public int id { get; set; }
        public int candidate_id { get; set; }
        public int emp_id { get; set; }
        public int client_id { get; set; }
        public string position { get; set; }
        public int emptype_id { get; set; }
        public int emprank_id { get; set; }
        public int branch_id { get; set; }
        public int department_id { get; set; }
        public int shift_id { get; set; }
        public int salarytype_id { get; set; }
        public System.DateTime datehired { get; set; }
        public decimal salary { get; set; }
        public int userid { get; set; }
        public System.DateTime datecreated { get; set; }
        public string hire_status { get; set; }
        public Nullable<System.DateTime> contract_start { get; set; }
        public Nullable<System.DateTime> contract_end { get; set; }
        public decimal salary_amount { get; set; }
        public decimal allowance_amount { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual REC_CANDIDATE REC_CANDIDATE { get; set; }
        public virtual SYS_USER SYS_USER { get; set; }
    }
}
