//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_CLIENT_ACCOUNT_MAPPING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REC_CLIENT_ACCOUNT_MAPPING()
        {
            this.REC_CLIENT_ACCOUNT_MAP_FIELD = new HashSet<REC_CLIENT_ACCOUNT_MAP_FIELD>();
        }
    
        public int id { get; set; }
        public int client_id { get; set; }
        public decimal sort_no { get; set; }
        public string acct_code { get; set; }
        public string account_description { get; set; }
        public string account_type { get; set; }
        public bool is_minimum { get; set; }
        public bool by_dept { get; set; }
        public int dept_id { get; set; }
        public string mapping_cnt { get; set; }
        public string entry_type { get; set; }
        public int user_id { get; set; }
        public System.DateTime date_created { get; set; }
    
        public virtual REC_CLIENT REC_CLIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REC_CLIENT_ACCOUNT_MAP_FIELD> REC_CLIENT_ACCOUNT_MAP_FIELD { get; set; }
    }
}
