//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_NEW_HIRED_EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REC_NEW_HIRED_EMPLOYEE()
        {
            this.REC_NEW_HIRED_EMPLOYEE_REMARKS = new HashSet<REC_NEW_HIRED_EMPLOYEE_REMARKS>();
        }
    
        public int id { get; set; }
        public int client_id { get; set; }
        public int emp_id { get; set; }
        public System.DateTime date_hired { get; set; }
        public Nullable<System.DateTime> contract_start { get; set; }
        public Nullable<System.DateTime> contract_end { get; set; }
        public bool is_history { get; set; }
        public int user_id { get; set; }
        public System.DateTime date_created { get; set; }
        public string hire_type { get; set; }
        public int jo_det_id { get; set; }
        public Nullable<System.DateTime> date_resignation_submitted { get; set; }
        public Nullable<System.DateTime> date_separated { get; set; }
        public int separated_by { get; set; }
        public int floating_id { get; set; }
        public Nullable<System.DateTime> date_inactive { get; set; }
        public Nullable<System.DateTime> date_inactive_created { get; set; }
        public int inactive_by { get; set; }
        public int separated_id { get; set; }
        public Nullable<System.DateTime> date_closed { get; set; }
        public int employee_type_id { get; set; }
        public string position { get; set; }
        public Nullable<System.DateTime> date_regularized { get; set; }
        public decimal salary_amount { get; set; }
        public string salary_type { get; set; }
        public bool contract_extended { get; set; }
        public int department_id { get; set; }
        public int branch_id { get; set; }
        public Nullable<System.DateTime> date_contract_extended { get; set; }
        public int extended_from_contract_id { get; set; }
        public int employee_rank_id { get; set; }
        public int restday_id { get; set; }
        public int shift_id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual EmployeeType EmployeeType { get; set; }
        public virtual REC_CLIENT REC_CLIENT { get; set; }
        public virtual SYS_USER SYS_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REC_NEW_HIRED_EMPLOYEE_REMARKS> REC_NEW_HIRED_EMPLOYEE_REMARKS { get; set; }
    }
}
