//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_CLIENT_SETUP_EXT
    {
        public int id { get; set; }
        public int client_id { get; set; }
        public bool Proc_billing_rate { get; set; }
        public bool proc_processing_fee { get; set; }
        public bool term_thirty { get; set; }
        public bool term_fourtyfive { get; set; }
        public bool term_sixty { get; set; }
        public bool term_ninety { get; set; }
        public bool comp_all { get; set; }
        public bool comp_salary_overtime { get; set; }
        public bool comp_salary_only { get; set; }
        public bool comp_overtime_only { get; set; }
        public bool comp_adjustment_only { get; set; }
        public bool term_fifteen { get; set; }
        public bool term_immediate { get; set; }
        public bool proc_billing_card { get; set; }
        public bool term_forty { get; set; }
        public bool term_twenty { get; set; }
    
        public virtual REC_CLIENT REC_CLIENT { get; set; }
    }
}
