//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_CANDIDATE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REC_CANDIDATE()
        {
            this.REC_CANDIDATE_EMPLOYEE_LINK = new HashSet<REC_CANDIDATE_EMPLOYEE_LINK>();
        }
    
        public int id { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public System.DateTime birthday { get; set; }
        public string gender { get; set; }
        public string civil_status { get; set; }
        public string mobile_no { get; set; }
        public int status { get; set; }
        public Nullable<bool> file_status { get; set; }
        public Nullable<int> usermodified { get; set; }
        public System.DateTime date_modified { get; set; }
        public int user_id { get; set; }
        public System.DateTime date_encoded { get; set; }
        public string position_applied { get; set; }
        public string height { get; set; }
        public string weight { get; set; }
        public string religion { get; set; }
        public string birth_place { get; set; }
        public string contact_no { get; set; }
        public string nationality { get; set; }
        public string email_address { get; set; }
        public string present_address { get; set; }
        public int city_id { get; set; }
        public string provincial_address { get; set; }
        public int province_id { get; set; }
        public string contact_person { get; set; }
        public string contact_person_contact { get; set; }
        public string contact_relation { get; set; }
        public string contact_address { get; set; }
        public System.DateTime date_applied { get; set; }
        public bool is_convicted_of_felony { get; set; }
        public string conviction_details { get; set; }
        public Nullable<int> employment_availability { get; set; }
        public Nullable<int> hours_available { get; set; }
        public bool with_previous_application { get; set; }
        public Nullable<System.DateTime> previous_date_applied { get; set; }
        public string how_referred_to_us { get; set; }
        public string referral_details { get; set; }
        public string change_employment_reason { get; set; }
        public bool is_discharged_from_position { get; set; }
        public int contract_type_id { get; set; }
        public int source_id { get; set; }
        public string encoded_from { get; set; }
        public int function_id { get; set; }
        public string availability { get; set; }
        public string about_candidate { get; set; }
        public string current_position { get; set; }
        public Nullable<System.DateTime> current_position_from { get; set; }
        public Nullable<System.DateTime> current_position_to { get; set; }
        public int work_location_id { get; set; }
        public int working_setup_id { get; set; }
        public decimal asking_salary { get; set; }
        public string asking_salary_type { get; set; }
        public int industry_id { get; set; }
        public string shift_desired { get; set; }
        public int motivation_id { get; set; }
        public string communication_skill { get; set; }
        public int total_years_of_experience { get; set; }
        public int ads_seen_id { get; set; }
        public string created_type { get; set; }
        public string guid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REC_CANDIDATE_EMPLOYEE_LINK> REC_CANDIDATE_EMPLOYEE_LINK { get; set; }
        public virtual SYS_USER SYS_USER { get; set; }
    }
}
