//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_CLIENT_SETUP_CUTOFF
    {
        public int id { get; set; }
        public int client_id { get; set; }
        public string first_cutoff_from_month { get; set; }
        public int first_cutoff_from_day { get; set; }
        public string first_cutoff_to_month { get; set; }
        public int first_cutoff_to_day { get; set; }
        public string second_cutoff_from_month { get; set; }
        public int second_cutoff_from_day { get; set; }
        public string second_cutoff_to_month { get; set; }
        public int second_cutoff_to_day { get; set; }
        public int user_id { get; set; }
        public System.DateTime date_created { get; set; }
    }
}
