//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_CLIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REC_CLIENT()
        {
            this.Employees = new HashSet<Employee>();
            this.Employees1 = new HashSet<Employee>();
            this.EmployeeLeaveMonitorings = new HashSet<EmployeeLeaveMonitoring>();
            this.P_Leave = new HashSet<P_Leave>();
            this.Branches = new HashSet<Branch>();
            this.REC_CLIENT_DEPARTMENT = new HashSet<REC_CLIENT_DEPARTMENT>();
            this.REC_CLIENT_SHIFT = new HashSet<REC_CLIENT_SHIFT>();
            this.REC_NEW_HIRED_EMPLOYEE = new HashSet<REC_NEW_HIRED_EMPLOYEE>();
            this.REC_CLIENT_COMPANY = new HashSet<REC_CLIENT_COMPANY>();
            this.Adjustments = new HashSet<Adjustment>();
            this.Deductions = new HashSet<Deduction>();
            this.REC_CLIENT_BANK = new HashSet<REC_CLIENT_BANK>();
            this.REC_CLIENT_CONTACTS = new HashSet<REC_CLIENT_CONTACTS>();
            this.REC_CLIENT_DOCUMENTS = new HashSet<REC_CLIENT_DOCUMENTS>();
            this.REC_JOB_ORDER = new HashSet<REC_JOB_ORDER>();
            this.REC_CLIENT_SETUP = new HashSet<REC_CLIENT_SETUP>();
            this.REC_CLIENT_SETUP_EXT = new HashSet<REC_CLIENT_SETUP_EXT>();
        }
    
        public int id { get; set; }
        public string client_name { get; set; }
        public string client_address { get; set; }
        public string contact_no { get; set; }
        public string email_address { get; set; }
        public string contact_person { get; set; }
        public string remarks { get; set; }
        public Nullable<bool> status { get; set; }
        public string tin_no { get; set; }
        public int industry_id { get; set; }
        public string contact_title { get; set; }
        public string mobile_no { get; set; }
        public Nullable<System.DateTime> date_encoded { get; set; }
        public string website { get; set; }
        public int userid { get; set; }
        public bool Vatable { get; set; }
        public string client_type { get; set; }
        public byte[] logofile { get; set; }
        public string zip_code { get; set; }
        public string sss_no { get; set; }
        public string sss_br_code { get; set; }
        public string pagibig_no { get; set; }
        public string pagibig_br_code { get; set; }
        public string philhealth_no { get; set; }
        public string philhealth_br_code { get; set; }
        public string company_type { get; set; }
        public bool is_withholding_tax { get; set; }
        public decimal withholding_tax_rate { get; set; }
        public string Vat_Type { get; set; }
        public string billing_address { get; set; }
        public int employer_id { get; set; }
        public string guid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLeaveMonitoring> EmployeeLeaveMonitorings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_Leave> P_Leave { get; set; }
        public virtual SYS_USER SYS_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Branch> Branches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REC_CLIENT_DEPARTMENT> REC_CLIENT_DEPARTMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REC_CLIENT_SHIFT> REC_CLIENT_SHIFT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REC_NEW_HIRED_EMPLOYEE> REC_NEW_HIRED_EMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REC_CLIENT_COMPANY> REC_CLIENT_COMPANY { get; set; }
        public virtual INDUSTRY INDUSTRY { get; set; }
        public virtual EMPLOYER EMPLOYER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adjustment> Adjustments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deduction> Deductions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REC_CLIENT_BANK> REC_CLIENT_BANK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REC_CLIENT_CONTACTS> REC_CLIENT_CONTACTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REC_CLIENT_DOCUMENTS> REC_CLIENT_DOCUMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REC_JOB_ORDER> REC_JOB_ORDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REC_CLIENT_SETUP> REC_CLIENT_SETUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REC_CLIENT_SETUP_EXT> REC_CLIENT_SETUP_EXT { get; set; }
    }
}
