//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_CANDIDATE_TRAINING
    {
        public int id { get; set; }
        public int candidate_id { get; set; }
        public int training_id { get; set; }
        public string venue { get; set; }
        public Nullable<System.DateTime> date_from { get; set; }
        public Nullable<System.DateTime> date_to { get; set; }
        public string facilitator { get; set; }
        public string remarks { get; set; }
        public string file_location { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Internal { get; set; }
        public Nullable<decimal> NoOfHours { get; set; }
    
        public virtual REC_CANDIDATE REC_CANDIDATE { get; set; }
    }
}
