//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_CLIENT_ACCOUNT_MAP_FIELD
    {
        public int id { get; set; }
        public int map_id { get; set; }
        public int entry_id { get; set; }
        public System.DateTime date_added { get; set; }
        public int user_id { get; set; }
    
        public virtual REC_CLIENT_ACCOUNT_MAPPING REC_CLIENT_ACCOUNT_MAPPING { get; set; }
    }
}
