//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_CLIENT_SETUP
    {
        public int id { get; set; }
        public int client_id { get; set; }
        public decimal working_days { get; set; }
        public decimal source_rate { get; set; }
        public decimal endorse_rate { get; set; }
        public decimal seasonal_rate { get; set; }
        public int sss_sched { get; set; }
        public int philhealth_sched { get; set; }
        public int pagibig_sched { get; set; }
        public int sss_loan_sched { get; set; }
        public int pagibig_loan_sched { get; set; }
        public int allowance_sched { get; set; }
        public int meal_allowance_sched { get; set; }
        public int rice_allowance_sched { get; set; }
        public int philhealth_computation { get; set; }
        public int sss_computation { get; set; }
        public int ps_max_process_employee_count { get; set; }
        public decimal ps_regular_process_fee { get; set; }
        public decimal ps_special_process_fee { get; set; }
        public decimal ps_one_time_fee { get; set; }
        public decimal ps_additional_fee { get; set; }
        public decimal rope_admin_fee { get; set; }
        public int payroll_payment_1st_cutoff { get; set; }
        public int payroll_payment_2nd_cutoff { get; set; }
        public int other_loan_sched { get; set; }
        public bool is_include_thirteen { get; set; }
        public bool is_include_separation_pay { get; set; }
        public bool is_include_hmo { get; set; }
        public bool is_include_silp { get; set; }
        public bool is_include_allowance { get; set; }
        public string separation_pay_basis { get; set; }
        public string thirteen_month_pay_basis { get; set; }
        public decimal silp_days { get; set; }
        public decimal hmo_amount { get; set; }
        public bool is_include_ward { get; set; }
        public decimal ward_amount { get; set; }
        public string silp_basis { get; set; }
        public string sep_pay_basis { get; set; }
        public int overtime_setup_id { get; set; }
        public decimal insurance_amount { get; set; }
        public bool include_insurance { get; set; }
        public string allowance_deduct_basis { get; set; }
        public bool include_adjustment { get; set; }
        public string adjustment_basis { get; set; }
    
        public virtual REC_CLIENT REC_CLIENT { get; set; }
        public virtual OvertimeBasi OvertimeBasi { get; set; }
    }
}
