//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_CLIENT_OT_RATE
    {
        public int id { get; set; }
        public int client_id { get; set; }
        public decimal reg_ot_rate { get; set; }
        public decimal reg_ot_n8_rate { get; set; }
        public decimal reg_ot_nd_rate { get; set; }
        public decimal rest_day_ot_rate { get; set; }
        public decimal rest_day_ot_n8_rate { get; set; }
        public decimal rest_day_ot_nd_rate { get; set; }
        public decimal spc_hol_ot_rate { get; set; }
        public decimal spc_hol_ot_n8_rate { get; set; }
        public decimal spc_hol_ot_nd_rate { get; set; }
        public decimal legal_hol_ot_rate { get; set; }
        public decimal legal_hol_ot_n8_rate { get; set; }
        public decimal legal_hol_ot_nd_rate { get; set; }
        public decimal rest_day_spc_hol_ot_rate { get; set; }
        public decimal rest_day_spc_hol_ot_n8_rate { get; set; }
        public decimal rest_day_spc_hol_ot_nd_rate { get; set; }
        public decimal rest_day_legal_hol_ot_rate { get; set; }
        public decimal rest_day_legal_hol_n8_ot_rate { get; set; }
        public decimal rest_day_legal_hol_nd_ot_rate { get; set; }
        public decimal spc_hol_ot_rate_daily { get; set; }
        public decimal leg_hol_ot_rate_daily { get; set; }
    
        public virtual REC_CLIENT REC_CLIENT { get; set; }
    }
}
