//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_CANDIDATE_EMPLOYMENT
    {
        public int candidate_id { get; set; }
        public string Company_name { get; set; }
        public string Company_Address { get; set; }
        public string Company_position { get; set; }
        public string Company_Rank { get; set; }
        public string Reason_for_leaving { get; set; }
        public Nullable<decimal> Company_Salary { get; set; }
        public Nullable<System.DateTime> Company_from { get; set; }
        public Nullable<System.DateTime> Company_to { get; set; }
        public int User_Id { get; set; }
        public int Employ_ID { get; set; }
        public string Emidiate_head { get; set; }
        public string employment_Status { get; set; }
        public Nullable<int> Internal_Tag { get; set; }
        public Nullable<int> NatureOfBusinessID { get; set; }
        public System.DateTime date_created { get; set; }
        public int function_id { get; set; }
        public int industry_id { get; set; }
        public int role_id { get; set; }
        public bool fixed_bonus_13 { get; set; }
        public bool fixed_bonus_14 { get; set; }
        public bool fixed_bonus_15 { get; set; }
        public bool fixed_bonus_16 { get; set; }
        public bool hmo_principal { get; set; }
        public bool hmo_dependent { get; set; }
        public bool is_tax_shield { get; set; }
        public int tax_shield_percentage { get; set; }
        public string other_benifits { get; set; }
        public string job_description { get; set; }
        public bool is_currently_working { get; set; }
        public int company_id { get; set; }
    
        public virtual REC_CANDIDATE REC_CANDIDATE { get; set; }
    }
}
