//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_CANDIDATE_DOCUMENT
    {
        public int id { get; set; }
        public int candidate_id { get; set; }
        public int doc_id { get; set; }
        public Nullable<System.DateTime> date_issued { get; set; }
        public Nullable<System.DateTime> date_expired { get; set; }
        public string remarks { get; set; }
        public string file_location { get; set; }
        public string DocNo { get; set; }
        public System.DateTime date_added { get; set; }
        public int added_by { get; set; }
    
        public virtual REC_CANDIDATE REC_CANDIDATE { get; set; }
        public virtual SYS_USER SYS_USER { get; set; }
    }
}
