//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_CLIENT_DOCUMENTS
    {
        public int id { get; set; }
        public int client_id { get; set; }
        public int doc_id { get; set; }
        public string doc_no { get; set; }
        public Nullable<System.DateTime> date_issued { get; set; }
        public Nullable<System.DateTime> date_expired { get; set; }
        public string file_location { get; set; }
        public string remarks { get; set; }
        public int user_created { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<int> user_modified { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public string file_extension { get; set; }
        public Nullable<bool> is_notarized { get; set; }
        public Nullable<bool> is_signed { get; set; }
        public Nullable<bool> is_withoriginal { get; set; }
        public Nullable<bool> is_history { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual REC_CLIENT REC_CLIENT { get; set; }
        public virtual SYS_USER SYS_USER { get; set; }
    }
}
