//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_CLIENT_COMPANY
    {
        public int id { get; set; }
        public int client_id { get; set; }
        public int company_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime date_created { get; set; }
    
        public virtual REC_CLIENT REC_CLIENT { get; set; }
        public virtual SYS_USER SYS_USER { get; set; }
        public virtual sys_company sys_company { get; set; }
    }
}
