//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class REC_CLIENT_PORTAL_RULE
    {
        public int id { get; set; }
        public int client_Id { get; set; }
        public bool follow_atd_correction_filing_rule { get; set; }
        public int no_of_allowed_days_for_filing_atd_correction { get; set; }
        public bool follow_overtime_filing_rule { get; set; }
        public int no_of_allowed_days_for_overtime { get; set; }
        public bool follow_vacation_leave_filing_rule { get; set; }
        public int no_of_allowed_days_for_filing_vacation_leave { get; set; }
        public bool follow_sick_leave_filing_rule { get; set; }
        public int no_of_allowed_days_for_filing_sick_leave { get; set; }
        public string when_can_a_birthday_leave_be_filed { get; set; }
        public int allowed_minimum_minute_of_overtime { get; set; }
        public int allowed_succeeding_minute_of_overtime { get; set; }
        public bool follow_dtr_validation_rule { get; set; }
        public bool use_employee_digital_signature { get; set; }
        public bool use_coordinator_digital_signature { get; set; }
        public bool use_approver_digital_signature { get; set; }
        public bool enable_attendance_email_notification { get; set; }
        public bool enable_attendance_shift_reminder { get; set; }
        public System.DateTime date_created { get; set; }
        public bool automatic_no_break_ot { get; set; }
        public bool implement_proximity_attendance { get; set; }
        public bool implement_dtr_posting_checking { get; set; }
        public bool allowed_blank_attendance_coordinates { get; set; }
        public bool is_client_approve_the_dtr { get; set; }
        public bool is_location_required { get; set; }
    }
}
