//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Required_Document_details
    {
        public int id { get; set; }
        public int req_id { get; set; }
        public int doc_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime date_created { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Required_Document Required_Document { get; set; }
        public virtual SYS_USER SYS_USER { get; set; }
    }
}
