//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shift()
        {
            this.Employees = new HashSet<Employee>();
            this.REC_CLIENT_SHIFT = new HashSet<REC_CLIENT_SHIFT>();
        }
    
        public int Shift_ID { get; set; }
        public string Description { get; set; }
        public System.DateTime Shift_in { get; set; }
        public System.DateTime Shift_out { get; set; }
        public int Grace_period { get; set; }
        public int UserID { get; set; }
        public bool status { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime break_time_start { get; set; }
        public System.DateTime break_time_end { get; set; }
        public bool is_graveyard { get; set; }
        public int country_id { get; set; }
        public Nullable<System.DateTime> grave_time_in { get; set; }
        public Nullable<System.DateTime> grave_time_out { get; set; }
        public bool is_halfday { get; set; }
        public bool is_compress { get; set; }
        public decimal hours_worked { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REC_CLIENT_SHIFT> REC_CLIENT_SHIFT { get; set; }
        public virtual SYS_USER SYS_USER { get; set; }
    }
}
