//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sys_company()
        {
            this.SYS_USER_GROUP = new HashSet<SYS_USER_GROUP>();
        }
    
        public int id { get; set; }
        public string company_code { get; set; }
        public string company_name { get; set; }
        public string address { get; set; }
        public string trunk_no { get; set; }
        public string fax_no { get; set; }
        public string TIN_no { get; set; }
        public bool status { get; set; }
        public int user_id { get; set; }
        public System.DateTime date_created { get; set; }
        public string CompanyWebsite { get; set; }
        public string CompanyLogo { get; set; }
        public int country_id { get; set; }
    
        public virtual SYS_USER SYS_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_USER_GROUP> SYS_USER_GROUP { get; set; }
    }
}
