//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Module
    {
        public int MODULEID { get; set; }
        public int MODULE_TYPE { get; set; }
        public string MODULE_NAME { get; set; }
        public int MODULE_APP { get; set; }
        public int ACTIVE { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
    
        public virtual sys_module_type sys_module_type { get; set; }
    }
}
