//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAMS_LOCAL_HOLIDAY_DET
    {
        public int id { get; set; }
        public int holiday_id { get; set; }
        public int emp_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime date_created { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual SYS_USER SYS_USER { get; set; }
    }
}
