//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    
    public partial class USP_S_GET_PORTAL_USER_Result2
    {
        public Nullable<int> userid { get; set; }
        public Nullable<int> empid { get; set; }
        public string username { get; set; }
        public string clientname { get; set; }
        public string employeename { get; set; }
        public string email_address { get; set; }
        public Nullable<bool> status { get; set; }
        public string user_status { get; set; }
        public Nullable<System.DateTime> date_registered { get; set; }
    }
}
