//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    
    public partial class USP_H_GET_HELPDESK_MONITORING_Result1
    {
        public Nullable<int> id { get; set; }
        public Nullable<System.DateTime> concern_date { get; set; }
        public string client { get; set; }
        public string concern_type { get; set; }
        public string concern_description { get; set; }
        public string file_status { get; set; }
        public string concern_status { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> date_completed { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<System.DateTime> date_posted { get; set; }
    }
}
