//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    
    public partial class USP_S_GET_PORTAL_USER_Result1
    {
        public int UserID { get; set; }
        public int EmpID { get; set; }
        public string USERNAME { get; set; }
        public string client_name { get; set; }
        public string Column1 { get; set; }
        public string EmailAddress { get; set; }
        public bool Status { get; set; }
        public string UserStatus { get; set; }
        public Nullable<System.DateTime> DateReg { get; set; }
    }
}
