//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.DB
{
    using System;
    
    public partial class USP_S_GET_ASSIGNED_MODULES_Result2
    {
        public Nullable<int> id { get; set; }
        public Nullable<int> module_id { get; set; }
        public string module_name { get; set; }
        public Nullable<bool> access_add { get; set; }
        public Nullable<bool> access_edit { get; set; }
        public Nullable<bool> access_delete { get; set; }
        public Nullable<bool> access_print { get; set; }
        public Nullable<bool> access_post { get; set; }
        public Nullable<bool> access_unpost { get; set; }
        public Nullable<bool> access_cancel { get; set; }
        public Nullable<bool> access_activate { get; set; }
        public Nullable<bool> access_deactivate { get; set; }
        public string provided_by { get; set; }
        public Nullable<System.DateTime> date_provided { get; set; }
    }
}
